### ISSUE TITLE
CT cannot read properties of undefined reading colorUtilsDarker

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#10]
```
build-a-nucleus : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645705804436%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'colorUtilsDarker')
TypeError: Cannot read properties of undefined (reading 'colorUtilsDarker')
at new nk (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645705804436%7D&fuzz&memoryLimit=1000:894:1314609)
at r (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645705804436%7D&fuzz&memoryLimit=1000:894:1341557)
at l (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645705804436%7D&fuzz&memoryLimit=1000:894:1342051)
at new tL (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645705804436%7D&fuzz&memoryLimit=1000:894:1342287)
at new iL (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645705804436%7D&fuzz&memoryLimit=1000:894:1343246)
at rL.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645705804436%7D&fuzz&memoryLimit=1000:894:1343644)
at rL.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645705804436%7D&fuzz&memoryLimit=1000:894:1015973)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645705804436%7D&fuzz&memoryLimit=1000:894:1271856)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645705804436%7D&fuzz&memoryLimit=1000:894:1272009
id: Bayes Chrome
Snapshot from 2/24/2022, 4:08:45 AM

----------------------------------

build-a-nucleus : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645719442880%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'colorUtilsDarker')
TypeError: Cannot read properties of undefined (reading 'colorUtilsDarker')
at new nk (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645719442880%7D&fuzz&memoryLimit=1000:894:1314609)
at r (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645719442880%7D&fuzz&memoryLimit=1000:894:1341557)
at l (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645719442880%7D&fuzz&memoryLimit=1000:894:1342051)
at new tL (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645719442880%7D&fuzz&memoryLimit=1000:894:1342287)
at new iL (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645719442880%7D&fuzz&memoryLimit=1000:894:1343246)
at rL.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645719442880%7D&fuzz&memoryLimit=1000:894:1343644)
at rL.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645719442880%7D&fuzz&memoryLimit=1000:894:1015973)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645719442880%7D&fuzz&memoryLimit=1000:894:1271856)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645719442880%7D&fuzz&memoryLimit=1000:894:1272009
id: Bayes Chrome
Snapshot from 2/24/2022, 4:08:45 AM

----------------------------------

build-a-nucleus : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645706203479%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Unrecognized particle type: positron
Error: Assertion failed: Unrecognized particle type: positron
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/assert/js/assert.js:25:13)
at new ParticleNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/shred/js/view/ParticleNode.js:43:15)
at createParticleNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/AvailableDecaysPanel.js:66:14)
at createBetaDecayIcon (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/AvailableDecaysPanel.js:105:65)
at new AvailableDecaysPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/AvailableDecaysPanel.js:128:7)
at new DecayScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/DecayScreenView.js:28:34)
at DecayScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/DecayScreen.js:27:18)
at DecayScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/joist/js/Screen.js:202:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/joist/js/Sim.js:680:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/joist/js/Sim.js:687:21
id: Bayes Chrome
Snapshot from 2/24/2022, 4:08:45 AM

----------------------------------

build-a-nucleus : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645720492668%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Unrecognized particle type: positron
Error: Assertion failed: Unrecognized particle type: positron
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/assert/js/assert.js:25:13)
at new ParticleNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/shred/js/view/ParticleNode.js:43:15)
at createParticleNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/AvailableDecaysPanel.js:66:14)
at createBetaDecayIcon (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/AvailableDecaysPanel.js:105:65)
at new AvailableDecaysPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/AvailableDecaysPanel.js:128:7)
at new DecayScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/DecayScreenView.js:28:34)
at DecayScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/DecayScreen.js:27:18)
at DecayScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/joist/js/Screen.js:202:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/joist/js/Sim.js:680:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/joist/js/Sim.js:687:21
id: Bayes Chrome
Snapshot from 2/24/2022, 4:08:45 AM

----------------------------------

build-a-nucleus : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645718528098%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Unrecognized particle type: positron
Error: Assertion failed: Unrecognized particle type: positron
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/assert/js/assert.js:25:13)
at new ParticleNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/shred/js/view/ParticleNode.js:43:15)
at createParticleNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/AvailableDecaysPanel.js:66:14)
at createBetaDecayIcon (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/AvailableDecaysPanel.js:105:65)
at new AvailableDecaysPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/AvailableDecaysPanel.js:128:7)
at new DecayScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/DecayScreenView.js:28:34)
at DecayScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/DecayScreen.js:27:18)
at DecayScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/joist/js/Screen.js:202:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/joist/js/Sim.js:680:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/joist/js/Sim.js:687:21
id: Bayes Chrome
Snapshot from 2/24/2022, 4:08:45 AM

----------------------------------

build-a-nucleus : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645704470664%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Unrecognized particle type: positron
Error: Assertion failed: Unrecognized particle type: positron
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/assert/js/assert.js:25:13)
at new ParticleNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/shred/js/view/ParticleNode.js:43:15)
at createParticleNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/AvailableDecaysPanel.js:66:14)
at createBetaDecayIcon (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/AvailableDecaysPanel.js:105:65)
at new AvailableDecaysPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/AvailableDecaysPanel.js:128:7)
at new DecayScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/DecayScreenView.js:28:34)
at DecayScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/DecayScreen.js:27:18)
at DecayScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/joist/js/Screen.js:202:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/joist/js/Sim.js:680:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/joist/js/Sim.js:687:21
id: Bayes Chrome
Snapshot from 2/24/2022, 4:08:45 AM

----------------------------------

build-a-nucleus : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645720701522%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Unrecognized particle type: positron
Error: Assertion failed: Unrecognized particle type: positron
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/assert/js/assert.js:25:13)
at new ParticleNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/shred/js/view/ParticleNode.js:43:15)
at createParticleNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/AvailableDecaysPanel.js:66:14)
at createBetaDecayIcon (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/AvailableDecaysPanel.js:105:65)
at new AvailableDecaysPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/AvailableDecaysPanel.js:128:7)
at new DecayScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/DecayScreenView.js:28:34)
at DecayScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/DecayScreen.js:27:18)
at DecayScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/joist/js/Screen.js:202:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/joist/js/Sim.js:680:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/joist/js/Sim.js:687:21
id: Bayes Chrome
Snapshot from 2/24/2022, 4:08:45 AM

----------------------------------

build-a-nucleus : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645713089015%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Unrecognized particle type: positron
Error: Assertion failed: Unrecognized particle type: positron
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/assert/js/assert.js:25:13)
at new ParticleNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/shred/js/view/ParticleNode.js:43:15)
at createParticleNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/AvailableDecaysPanel.js:66:14)
at createBetaDecayIcon (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/AvailableDecaysPanel.js:105:65)
at new AvailableDecaysPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/AvailableDecaysPanel.js:128:7)
at new DecayScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/DecayScreenView.js:28:34)
at DecayScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/DecayScreen.js:27:18)
at DecayScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/joist/js/Screen.js:202:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/joist/js/Sim.js:680:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/joist/js/Sim.js:687:21
id: Bayes Chrome
Snapshot from 2/24/2022, 4:08:45 AM

----------------------------------

build-a-nucleus : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1645700925326%22%2C%22timestamp%22%3A1645720413670%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Unrecognized particle type: positron
Error: Assertion failed: Unrecognized particle type: positron
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/assert/js/assert.js:25:13)
at new ParticleNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/shred/js/view/ParticleNode.js:43:15)
at createParticleNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/AvailableDecaysPanel.js:66:14)
at createBetaDecayIcon (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/AvailableDecaysPanel.js:105:65)
at new AvailableDecaysPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/AvailableDecaysPanel.js:128:7)
at new DecayScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/view/DecayScreenView.js:28:34)
at DecayScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/build-a-nucleus/js/decay/DecayScreen.js:27:18)
at DecayScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/joist/js/Screen.js:202:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/joist/js/Sim.js:680:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645700925326/chipper/dist/js/joist/js/Sim.js:687:21
id: Bayes Chrome
Snapshot from 2/24/2022, 4:08:45 AM
```

**Comment by chrisklus** [comment]
Thanks @KatieWoe! @Luisav1 can you see if this is still happening?

**Comment by zepumph** [comment]
CT has been clear for the last 12 hours. Closing
