### ISSUE TITLE
CT Cannot set properties of undefined (setting 'inputEnabled')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#103]
```
build-a-nucleus : fuzz : built
http://127.0.0.1/continuous-testing/ct-snapshots/1690476738819/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1690476738819%22%2C%22timestamp%22%3A1690477988872%7D&fuzz
Query: fuzz
Uncaught TypeError: Cannot set properties of undefined (setting 'inputEnabled')
TypeError: Cannot set properties of undefined (setting 'inputEnabled')
at vy.animateAndRemoveParticle (http://127.0.0.1/continuous-testing/ct-snapshots/1690476738819/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1690476738819%22%2C%22timestamp%22%3A1690477988872%7D&fuzz:1042:1690962)
at vy.returnParticleToStack (http://127.0.0.1/continuous-testing/ct-snapshots/1690476738819/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1690476738819%22%2C%22timestamp%22%3A1690477988872%7D&fuzz:1042:1690865)
at V (http://127.0.0.1/continuous-testing/ct-snapshots/1690476738819/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1690476738819%22%2C%22timestamp%22%3A1690477988872%7D&fuzz:1042:1684284)
at P.xm.leftArrowFill (http://127.0.0.1/continuous-testing/ct-snapshots/1690476738819/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1690476738819%22%2C%22timestamp%22%3A1690477988872%7D&fuzz:1042:1683832)
at l.emit (http://127.0.0.1/continuous-testing/ct-snapshots/1690476738819/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1690476738819%22%2C%22timestamp%22%3A1690477988872%7D&fuzz:1042:23928)
at m.emit (http://127.0.0.1/continuous-testing/ct-snapshots/1690476738819/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1690476738819%22%2C%22timestamp%22%3A1690477988872%7D&fuzz:1042:7693)
at pi.fire (http://127.0.0.1/continuous-testing/ct-snapshots/1690476738819/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1690476738819%22%2C%22timestamp%22%3A1690477988872%7D&fuzz:1042:1195302)
at n (http://127.0.0.1/continuous-testing/ct-snapshots/1690476738819/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1690476738819%22%2C%22timestamp%22%3A1690477988872%7D&fuzz:1042:1194739)
at r.emit (http://127.0.0.1/continuous-testing/ct-snapshots/1690476738819/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1690476738819%22%2C%22timestamp%22%3A1690477988872%7D&fuzz:1042:23928)
at a._notifyListeners (http://127.0.0.1/continuous-testing/ct-snapshots/1690476738819/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1690476738819%22%2C%22timestamp%22%3A1690477988872%7D&fuzz:1042:17794)
id: Sparky Puppeteer
Snapshot from 7/27/2023, 10:52:18 AM

----------------------------------

build-a-nucleus : fuzz : unbuilt : listenerOrderRandom
http://127.0.0.1/continuous-testing/ct-snapshots/1690476738819/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1690476738819%22%2C%22timestamp%22%3A1690477025243%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1690476738819/assert/js/assert.js:28:13)
at assert (arrayRemove.js:19:12)
at arrayRemove (createObservableArray.ts:391:37)
at remove (BANModel.ts:148:19)
at removeParticle (ChartIntroModel.ts:82:10)
at removeParticle (BANScreenView.ts:656:15)
at removeParticle (BANScreenView.ts:643:13)
at (TinyEmitter.ts:136:42)
at emit (Emitter.ts:61:21)
at emit (Particle.ts:159:35)
id: Sparky Puppeteer
Snapshot from 7/27/2023, 10:52:18 AM
```

**Comment by marlitas** [comment]
@KatieWoe I think the assignments for this repo should switch to @zepumph and @Luisav1  since they are actively working on it. Thanks!

**Comment by zepumph** [comment]
I believe that this is fixed now. CT is clear. Closing. Commits over in https://github.com/phetsims/build-a-nucleus/issues/74 (sorry).
