### ISSUE TITLE
CT: Uncaught Error: Assertion failed: Bounds mismatch after validateBounds

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-a-nucleus#104]
Only when testing `?assertSlow`

```
build-a-nucleus : fuzz : unbuilt : assertSlow
http://128.138.93.172//continuous-testing/ct-snapshots/1690809568472/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1690809568472%22%2C%22timestamp%22%3A1690813141318%7D&brand=phet&eall&fuzz
Query: brand=phet&eall&fuzz
Uncaught Error: Assertion failed: Bounds mismatch after validateBounds: [x:(220.7373046875,449.2626953125),y:(162.90714285714284,196.90714285714284)], expected: [x:(235.7373046875,434.2626953125),y:(167.90714285714284,191.90714285714284)]. This could have happened if a bounds instance owned by a Node was directly mutated (e.g. bounds.erode())
Error: Assertion failed: Bounds mismatch after validateBounds: [x:(220.7373046875,449.2626953125),y:(162.90714285714284,196.90714285714284)], expected: [x:(235.7373046875,434.2626953125),y:(167.90714285714284,191.90714285714284)]. This could have happened if a bounds instance owned by a Node was directly mutated (e.g. bounds.erode())
at window.assertions.assertFunction (http://128.138.93.172//continuous-testing/ct-snapshots/1690809568472/assert/js/assert.js:28:13)
at assertSlow (Node.ts:1564:22)
at (Node.ts:1570:10)
at onAccessAttempt (TinyStaticProperty.ts:31:9)
at get (TinyProperty.ts:52:16)
at value (Node.ts:1984:31)
at getBounds (Node.ts:3061:16)
at getCenterX (Node.ts:3052:16)
at centerX (ChartIntroScreenView.ts:140:67)
at (ChartIntroScreen.ts:37:15)
[URL] http://128.138.93.172//continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1690809568472%2Fbuild-a-nucleus%2Fbuild-a-nucleus_en.html&simQueryParameters=brand%3Dphet%26eall%26fuzz&testInfo=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1690809568472%22%2C%22timestamp%22%3A1690813141318%7D
[NAVIGATED] http://128.138.93.172//continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1690809568472%2Fbuild-a-nucleus%2Fbuild-a-nucleus_en.html&simQueryParameters=brand%3Dphet%26eall%26fuzz&testInfo=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1690809568472%22%2C%22timestamp%22%3A1690813141318%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172//continuous-testing/ct-snapshots/1690809568472/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1690809568472%22%2C%22timestamp%22%3A1690813141318%7D&brand=phet&eall&fuzz
[CONSOLE] enabling assert
[CONSOLE] enabling assertSlow
[CONSOLE] Assertion failed: Bounds mismatch after validateBounds: [x:(220.7373046875,449.2626953125),y:(162.90714285714284,196.90714285714284)], expected: [x:(235.7373046875,434.2626953125),y:(167.90714285714284,191.90714285714284)]. This could have happened if a bounds instance owned by a Node was directly mutated (e.g. bounds.erode())
[PAGE ERROR] Error: Error: Assertion failed: Bounds mismatch after validateBounds: [x:(220.7373046875,449.2626953125),y:(162.90714285714284,196.90714285714284)], expected: [x:(235.7373046875,434.2626953125),y:(167.90714285714284,191.90714285714284)]. This could have happened if a bounds instance owned by a Node was directly mutated (e.g. bounds.erode())
at window.assertions.assertFunction (http://128.138.93.172//continuous-testing/ct-snapshots/1690809568472/assert/js/assert.js:28:13)
at http://128.138.93.172//continuous-testing/ct-snapshots/1690809568472/chipper/dist/js/scenery/js/nodes/Node.js:1316:23
at RichText.validateBounds (http://128.138.93.172//continuous-testing/ct-snapshots/1690809568472/chipper/dist/js/scenery/js/nodes/Node.js:1317:9)
at TinyStaticProperty.get (http://128.138.93.172//continuous-testing/ct-snapshots/1690809568472/chipper/dist/js/axon/js/TinyStaticProperty.js:26:10)
at get value [as value] (http://128.138.93.172//continuous-testing/ct-snapshots/1690809568472/chipper/dist/js/axon/js/TinyProperty.js:39:17)
at RichText.getBounds (http://128.138.93.172//continuous-testing/ct-snapshots/1690809568472/chipper/dist/js/scenery/js/nodes/Node.js:1707:32)
at RichText.getCenterX (http://128.138.93.172//continuous-testing/ct-snapshots/1690809568472/chipper/dist/js/scenery/js/nodes/Node.js:2742:17)
at get centerX [as centerX] (http://128.138.93.172//continuous-testing/ct-snapshots/1690809568472/chipper/dist/js/scenery/js/nodes/Node.js:2733:17)
at new ChartIntroScreenView (http://128.138.93.172//continuous-testing/ct-snapshots/1690809568472/chipper/dist/js/build-a-nucleus/js/chart-intro/view/ChartIntroScreenView.js:115:68)
at ChartIntroScreen.createView (http://128.138.93.172//continuous-testing/ct-snapshots/1690809568472/chipper/dist/js/build-a-nucleus/js/chart-intro/ChartIntroScreen.js:29:49)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 7/31/2023, 7:19:28 AM
```

```
build-a-nucleus : fuzz : unbuilt : assertSlow
http://127.0.0.1/continuous-testing/ct-snapshots/1690807075012/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1690807075012%22%2C%22timestamp%22%3A1690812876317%7D&brand=phet&eall&fuzz
Query: brand=phet&eall&fuzz
Error: Assertion failed: Bounds mismatch after validateBounds: [x:(220.75833129882812,449.2416687011719),y:(163.2071430478777,196.60714266640798)], expected: [x:(235.75833129882812,434.2416687011719),y:(168.2071430478777,191.60714266640798)]. This could have happened if a bounds instance owned by a Node was directly mutated (e.g. bounds.erode())
window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1690807075012/assert/js/assert.js:28:13
at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1690807075012/assert/js/assert.js:28:13)
at assertSlow (Node.ts:1564:22)
at (Node.ts:1570:10)
at onAccessAttempt (TinyStaticProperty.ts:31:9)
at get (TinyProperty.ts:52:16)
at (Node.ts:1984:4)
at getBounds (Node.ts:3061:16)
at getCenterX (Node.ts:3052:16)
at nuclearShellModelTextHighlight (ChartIntroScreenView.ts:140:4)
at (ChartIntroScreen.ts:37:15)
at createView (Screen.ts:307:22)
at initializeView (Sim.ts:868:15)
at (Sim.ts:876:25)
at (Sim.ts:874:16)
at i (Sim.ts:890:21)
at (Sim.ts:874:16)
at i (Sim.ts:890:21)
at (Sim.ts:874:16)
at i (Sim.ts:890:21)
at (Sim.ts:874:16)
at i (Sim.ts:890:21)
at (Sim.ts:874:16)
at i (Sim.ts:890:21)
at (Sim.ts:874:16)
at (Sim.ts:967:13)
at start (build-a-nucleus-main.ts:57:6)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:56:42)
at forEach (asyncLoader.ts:56:21)
at proceedIfReady (asyncLoader.ts:69:11)
at image (logo_png.ts:6:0)
id: Sparky Playwright Firefox
Snapshot from 7/31/2023, 6:37:55 AM
```

**Comment by zepumph** [comment]
Looks like https://github.com/phetsims/build-a-nucleus/issues/107 fixed this up in https://github.com/phetsims/build-a-nucleus/commit/62f83756332d1349704823355439d0caa9509a97. Not sure what the cause was, but that issue seemed like an easy common code update anyways. Closing
