### ISSUE TITLE
CT Cannot read properties of null (reading '_picker')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#14]
```
build-a-nucleus : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650498536373%22%2C%22timestamp%22%3A1650503260856%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of null (reading '_picker')
TypeError: Cannot read properties of null (reading '_picker')
at Ao.onInsertChild (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650498536373%22%2C%22timestamp%22%3A1650503260856%7D&fuzz&memoryLimit=1000:894:447398)
at fo.insertChild (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650498536373%22%2C%22timestamp%22%3A1650503260856%7D&fuzz&memoryLimit=1000:894:404255)
at fo.addChild (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650498536373%22%2C%22timestamp%22%3A1650503260856%7D&fuzz&memoryLimit=1000:894:404659)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650498536373%22%2C%22timestamp%22%3A1650503260856%7D&fuzz&memoryLimit=1000:894:1528866)
at ot.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650498536373%22%2C%22timestamp%22%3A1650503260856%7D&fuzz&memoryLimit=1000:894:42435)
at Dt._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650498536373%22%2C%22timestamp%22%3A1650503260856%7D&fuzz&memoryLimit=1000:894:84611)
at Dt.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650498536373%22%2C%22timestamp%22%3A1650503260856%7D&fuzz&memoryLimit=1000:894:83987)
at r_.reconfigureNucleus (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650498536373%22%2C%22timestamp%22%3A1650503260856%7D&fuzz&memoryLimit=1000:894:1451867)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650498536373%22%2C%22timestamp%22%3A1650503260856%7D&fuzz&memoryLimit=1000:894:1521354)
at s (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1650498536373%22%2C%22timestamp%22%3A1650503260856%7D&fuzz&memoryLimit=1000:894:76321)
id: Bayes Chrome
Snapshot from 4/20/2022, 5:48:56 PM

----------------------------------

build-a-nucleus : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1650498536373%22%2C%22timestamp%22%3A1650500296588%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/assert/js/assert.js:28:13)
at assert (arrayRemove.js:19:12)
at arrayRemove (createObservableArray.ts:417:37)
at remove (BANModel.ts:100:18)
at removeParticle (DecayScreenView.ts:287:69)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (Particle.js:142:35)
at step (BANModel.ts:114:14)
at Proxy.forEach
id: Bayes Chrome
Snapshot from 4/20/2022, 5:48:56 PM

----------------------------------

build-a-nucleus : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1650498536373%22%2C%22timestamp%22%3A1650520888256%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/assert/js/assert.js:28:13)
at assert (arrayRemove.js:19:12)
at arrayRemove (createObservableArray.ts:417:37)
at remove (BANModel.ts:100:18)
at removeParticle (DecayScreenView.ts:287:69)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (Particle.js:142:35)
at step (BANModel.ts:114:14)
at Proxy.forEach
id: Bayes Chrome
Snapshot from 4/20/2022, 5:48:56 PM

----------------------------------

build-a-nucleus : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1650498536373%22%2C%22timestamp%22%3A1650516797484%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/assert/js/assert.js:28:13)
at assert (arrayRemove.js:19:12)
at arrayRemove (createObservableArray.ts:417:37)
at remove (BANModel.ts:100:18)
at removeParticle (DecayScreenView.ts:287:69)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (Particle.js:142:35)
at step (BANModel.ts:114:14)
at Proxy.forEach
id: Bayes Chrome
Snapshot from 4/20/2022, 5:48:56 PM

----------------------------------

build-a-nucleus : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1650498536373%22%2C%22timestamp%22%3A1650500991378%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/assert/js/assert.js:28:13)
at assert (arrayRemove.js:19:12)
at arrayRemove (createObservableArray.ts:417:37)
at remove (BANModel.ts:100:18)
at removeParticle (DecayScreenView.ts:287:69)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (Particle.js:142:35)
at step (BANModel.ts:114:14)
at Proxy.forEach
id: Bayes Chrome
Snapshot from 4/20/2022, 5:48:56 PM

----------------------------------

build-a-nucleus : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1650498536373%22%2C%22timestamp%22%3A1650521834799%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/assert/js/assert.js:28:13)
at assert (arrayRemove.js:19:12)
at arrayRemove (createObservableArray.ts:417:37)
at remove (BANModel.ts:100:18)
at removeParticle (DecayScreenView.ts:287:69)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (Particle.js:142:35)
at step (BANModel.ts:114:14)
at Proxy.forEach
id: Bayes Chrome
Snapshot from 4/20/2022, 5:48:56 PM

----------------------------------

build-a-nucleus : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1650498536373%22%2C%22timestamp%22%3A1650504972616%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/assert/js/assert.js:28:13)
at assert (arrayRemove.js:19:12)
at arrayRemove (createObservableArray.ts:417:37)
at remove (BANModel.ts:100:18)
at removeParticle (DecayScreenView.ts:287:69)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (Particle.js:142:35)
at step (BANModel.ts:114:14)
at Proxy.forEach
id: Bayes Chrome
Snapshot from 4/20/2022, 5:48:56 PM

----------------------------------

build-a-nucleus : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1650498536373%22%2C%22timestamp%22%3A1650526565480%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/assert/js/assert.js:28:13)
at assert (arrayRemove.js:19:12)
at arrayRemove (createObservableArray.ts:417:37)
at remove (BANModel.ts:100:18)
at removeParticle (DecayScreenView.ts:287:69)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (Particle.js:142:35)
at step (BANModel.ts:114:14)
at Proxy.forEach
id: Bayes Chrome
Snapshot from 4/20/2022, 5:48:56 PM

----------------------------------

build-a-nucleus : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1650498536373%22%2C%22timestamp%22%3A1650518105351%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650498536373/assert/js/assert.js:28:13)
at assert (arrayRemove.js:19:12)
at arrayRemove (createObservableArray.ts:417:37)
at remove (BANModel.ts:100:18)
at removeParticle (DecayScreenView.ts:287:69)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (Particle.js:142:35)
at step (BANModel.ts:114:14)
at Proxy.forEach
id: Bayes Chrome
Snapshot from 4/20/2022, 5:48:56 PM
```

**Comment by chrisklus** [comment]
Thanks @KatieWoe! @Luisav1 could you take a look and see if this is still happening on CT? Thanks!

**Comment by KatieWoe** [comment]
CT doesn't look like it's finishing tasks at the moment, so it may be hard to tell.

**Comment by zepumph** [comment]
CT has been clear for the last 12 hours. Closing
