### ISSUE TITLE
CT item not found in array

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#17]
```
build-a-nucleus : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1652698808733%22%2C%22timestamp%22%3A1652713694505%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/assert/js/assert.js:28:13)
at assert (arrayRemove.js:19:12)
at arrayRemove (createObservableArray.ts:394:37)
at remove (BANModel.ts:100:19)
at removeParticle (DecayScreenView.ts:401:19)
at Proxy.forEach
at forEach (DecayScreenView.ts:400:28)
at listener (TinyEmitter.ts:93:8)
at emit (Emitter.ts:65:21)
at emit (Animation.js:321:24)
id: Bayes Chrome
Snapshot from 5/16/2022, 5:00:08 AM
```

**Comment by chrisklus** [comment]
Thanks @KatieWoe! @Luisav1 and I fixed this in the commit above and it hasn't shown up on CT since, closing.
