### ISSUE TITLE
 Assertion failed: The above cases should cover all possibilities

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-a-nucleus#179]
This is only showing up when shuffling listeners, so I will investigate this over in #105 
```
build-a-nucleus : fuzz : unbuilt : listenerOrderRandom
http://128.138.93.172//continuous-testing/ct-snapshots/1692891598609/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1692891598609%22%2C%22timestamp%22%3A1692894309443%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Assertion failed: The above cases should cover all possibilities
Error: Assertion failed: The above cases should cover all possibilities
at window.assertions.assertFunction (http://128.138.93.172//continuous-testing/ct-snapshots/1692891598609/assert/js/assert.js:28:13)
at assert (BANScreenView.ts:345:16)
at returnParticleToStack (NucleonArrowButtons.ts:277:9)
at decreaseNucleonNumberListener (NucleonArrowButtons.ts:140:19)
at listener (TinyEmitter.ts:122:8)
at emit (Emitter.ts:61:21)
at emit (PushButtonModel.ts:179:22)
at fire (PushButtonModel.ts:121:15)
at listener (TinyEmitter.ts:122:8)
at emit (ReadOnlyProperty.ts:315:22)
[URL] http://128.138.93.172//continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1692891598609%2Fbuild-a-nucleus%2Fbuild-a-nucleus_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1692891598609%22%2C%22timestamp%22%3A1692894309443%7D
[NAVIGATED] http://128.138.93.172//continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1692891598609%2Fbuild-a-nucleus%2Fbuild-a-nucleus_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1692891598609%22%2C%22timestamp%22%3A1692894309443%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172//continuous-testing/ct-snapshots/1692891598609/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1692891598609%22%2C%22timestamp%22%3A1692894309443%7D&brand=phet&ea&fuzz&listenerOrder=random
[CONSOLE] enabling assert
[CONSOLE] listenerOrder random seed: 527303
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: The above cases should cover all possibilities
[PAGE ERROR] Error: Error: Assertion failed: The above cases should cover all possibilities
at window.assertions.assertFunction (http://128.138.93.172//continuous-testing/ct-snapshots/1692891598609/assert/js/assert.js:28:13)
at ChartIntroScreenView.returnParticleToStack (http://128.138.93.172//continuous-testing/ct-snapshots/1692891598609/chipper/dist/js/build-a-nucleus/js/common/view/BANScreenView.js:271:17)
at NucleonArrowButtons.decreaseNucleonNumberListener (http://128.138.93.172//continuous-testing/ct-snapshots/1692891598609/chipper/dist/js/build-a-nucleus/js/common/view/NucleonArrowButtons.js:221:10)
at merge.leftArrowFill (http://128.138.93.172//continuous-testing/ct-snapshots/1692891598609/chipper/dist/js/build-a-nucleus/js/common/view/NucleonArrowButtons.js:101:165)
at TinyEmitter.emit (http://128.138.93.172//continuous-testing/ct-snapshots/1692891598609/chipper/dist/js/axon/js/TinyEmitter.js:94:9)
at Emitter.emit (http://128.138.93.172//continuous-testing/ct-snapshots/1692891598609/chipper/dist/js/axon/js/Emitter.js:50:22)
at PushButtonModel.fire (http://128.138.93.172//continuous-testing/ct-snapshots/1692891598609/chipper/dist/js/sun/js/buttons/PushButtonModel.js:134:23)
at downPropertyObserver (http://128.138.93.172//continuous-testing/ct-snapshots/1692891598609/chipper/dist/js/sun/js/buttons/PushButtonModel.js:79:16)
at TinyProperty.emit (http://128.138.93.172//continuous-testing/ct-snapshots/1692891598609/chipper/dist/js/axon/js/TinyEmitter.js:94:9)
at BooleanProperty._notifyListeners (http://128.138.93.172//continuous-testing/ct-snapshots/1692891598609/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:23)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 8/24/2023, 9:39:58 AM
```

**Comment by zepumph** [comment]
Fixed by https://github.com/phetsims/shred/commit/c6f44abb120d645fcd38f48c7c43dcb89ce35849 over in https://github.com/phetsims/build-a-nucleus/issues/105
