### ISSUE TITLE
CT Unexpected particle type.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#18]
```
build-a-nucleus : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654319562134%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Unexpected particle type.
Error: Unexpected particle type.
at (ParticleAtom.js:369:12)
at addParticle (DecayScreenView.ts:553:11)
at dragEndedListener (BANScreenView.ts:336:66)
at listener (TinyEmitter.ts:94:8)
at emit (Emitter.ts:66:21)
at emit (ParticleView.js:81:36)
at _end (DragListener.ts:393:24)
at callback (PressListener.ts:751:16)
at apply (PhetioAction.ts:124:16)
at execute (PressListener.ts:509:24)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

build-a-nucleus : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654396870986%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Unexpected particle type.
Error: Unexpected particle type.
at (ParticleAtom.js:369:12)
at addParticle (DecayScreenView.ts:553:11)
at dragEndedListener (BANScreenView.ts:336:66)
at listener (TinyEmitter.ts:94:8)
at emit (Emitter.ts:66:21)
at emit (ParticleView.js:81:36)
at _end (DragListener.ts:393:24)
at callback (PressListener.ts:751:16)
at apply (PhetioAction.ts:124:16)
at execute (PressListener.ts:509:24)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

build-a-nucleus : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654503450819%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Unexpected particle type.
Error: Unexpected particle type.
at (ParticleAtom.js:369:12)
at addParticle (DecayScreenView.ts:553:11)
at dragEndedListener (BANScreenView.ts:336:66)
at listener (TinyEmitter.ts:94:8)
at emit (Emitter.ts:66:21)
at emit (ParticleView.js:81:36)
at _end (DragListener.ts:393:24)
at callback (PressListener.ts:751:16)
at apply (PhetioAction.ts:124:16)
at execute (PressListener.ts:509:24)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

build-a-nucleus : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654306744466%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Unexpected particle type.
Error: Unexpected particle type.
at (ParticleAtom.js:369:12)
at addParticle (DecayScreenView.ts:553:11)
at dragEndedListener (BANScreenView.ts:336:66)
at listener (TinyEmitter.ts:94:8)
at emit (Emitter.ts:66:21)
at emit (ParticleView.js:81:36)
at _end (DragListener.ts:393:24)
at callback (PressListener.ts:751:16)
at apply (PhetioAction.ts:124:16)
at execute (PressListener.ts:509:24)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

build-a-nucleus : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654354525505%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Unexpected particle type.
Error: Unexpected particle type.
at (ParticleAtom.js:369:12)
at addParticle (DecayScreenView.ts:553:11)
at dragEndedListener (BANScreenView.ts:336:66)
at listener (TinyEmitter.ts:94:8)
at emit (Emitter.ts:66:21)
at emit (ParticleView.js:81:36)
at _end (DragListener.ts:393:24)
at callback (PressListener.ts:751:16)
at apply (PhetioAction.ts:124:16)
at execute (PressListener.ts:509:24)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

build-a-nucleus : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654368467435%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: The particleAtom needs a PROTON to emit it.
Error: Assertion failed: The particleAtom needs a PROTON to emit it.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/assert/js/assert.js:28:13)
at assert (DecayScreenView.ts:385:14)
at emitNucleon (DecayScreenView.ts:476:35)
at baseTimes (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/sherpa/lib/lodash-4.17.4.js:997:23)
at Function.times (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/sherpa/lib/lodash-4.17.4.js:16095:20)
at times (DecayScreenView.ts:476:12)
at listener (TinyEmitter.ts:94:8)
at emit (AbstractProperty.ts:255:22)
at _notifyListeners (AbstractProperty.ts:206:13)
at set (Property.ts:67:10)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

build-a-nucleus : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654387187703%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Unexpected particle type.
Error: Unexpected particle type.
at (ParticleAtom.js:369:12)
at addParticle (DecayScreenView.ts:553:11)
at dragEndedListener (BANScreenView.ts:336:66)
at listener (TinyEmitter.ts:94:8)
at emit (Emitter.ts:66:21)
at emit (ParticleView.js:81:36)
at _end (DragListener.ts:393:24)
at callback (PressListener.ts:751:16)
at apply (PhetioAction.ts:124:16)
at execute (PressListener.ts:509:24)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

build-a-nucleus : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654456657039%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Unexpected particle type.
Error: Unexpected particle type.
at (ParticleAtom.js:369:12)
at addParticle (DecayScreenView.ts:553:11)
at dragEndedListener (BANScreenView.ts:336:66)
at listener (TinyEmitter.ts:94:8)
at emit (Emitter.ts:66:21)
at emit (ParticleView.js:81:36)
at _end (DragListener.ts:393:24)
at callback (PressListener.ts:751:16)
at apply (PhetioAction.ts:124:16)
at execute (PressListener.ts:509:24)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

build-a-nucleus : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654517137681%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: reentry detected, value=Vector2(271.96742271791874, -164.21635418000506), oldValue=Vector2(270.1697154856001, -163.1308825282014)
Error: Assertion failed: reentry detected, value=Vector2(271.96742271791874, -164.21635418000506), oldValue=Vector2(270.1697154856001, -163.1308825282014)
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/assert/js/assert.js:28:13)
at assert (AbstractProperty.ts:252:14)
at _notifyListeners (AbstractProperty.ts:206:13)
at set (Property.ts:67:10)
at set (Property.ts:53:9)
at (AnimationTarget.js:296:6)
at setValue (AnimationTarget.js:331:9)
at update (Animation.js:308:24)
at listener (TinyEmitter.ts:94:8)
at emit (Sim.ts:447:16)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

build-a-nucleus : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654530178779%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: The particleAtom needs a PROTON to emit it.
Error: Assertion failed: The particleAtom needs a PROTON to emit it.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/assert/js/assert.js:28:13)
at assert (DecayScreenView.ts:385:14)
at emitNucleon (DecayScreenView.ts:476:35)
at baseTimes (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/sherpa/lib/lodash-4.17.4.js:997:23)
at Function.times (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/sherpa/lib/lodash-4.17.4.js:16095:20)
at times (DecayScreenView.ts:476:12)
at listener (TinyEmitter.ts:94:8)
at emit (AbstractProperty.ts:255:22)
at _notifyListeners (AbstractProperty.ts:206:13)
at set (Property.ts:67:10)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM
```

**Comment by KatieWoe** [comment]
This was found in https://github.com/phetsims/qa/issues/809 while doing a fuzz test on the debug version of the sim:
<img width="346" alt="indebug" src="https://user-images.githubusercontent.com/41024075/172452878-70e68cd1-0439-487b-99c3-e848875c7d28.png">

**Comment by Luisav1** [comment]
Thanks @KatieWoe and @Nancy-Salpepi! @chrisklus and I hopefully fixed this in the commits above but we'll monitor CT to see if it comes up again.

**Comment by Luisav1** [comment]
We didn't see this issue come up in CT again so it seems fixed. Closing.
