### ISSUE TITLE
CT: Cannot step a particle that's already been disposed.

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#202]
This has been appearing on CT often.
```js
build-a-nucleus : fuzz : unbuilt : query-parameters
http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1696434674419%22%2C%22timestamp%22%3A1696435257585%7D&brand=phet&ea&fuzz&decayScreenProtons=58&decayScreenNeutrons=92&chartIntoScreenProtons=8&chartIntoScreenNeutrons=12
Query: brand=phet&ea&fuzz&decayScreenProtons=58&decayScreenNeutrons=92&chartIntoScreenProtons=8&chartIntoScreenNeutrons=12
Uncaught Error: Assertion failed: cannot step a particle that has already been disposed
Error: Assertion failed: cannot step a particle that has already been disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/assert/js/assert.js:28:13)
at assert (BANModel.ts:215:16)
at Proxy.forEach
at forEach (BANModel.ts:214:19)
at step (DecayModel.ts:121:10)
at step (Sim.ts:417:21)
at apply (PhetioAction.ts:161:16)
at execute (Sim.ts:1017:30)
at stepSimulation (Sim.ts:1007:11)
at stepOneFrame (Sim.ts:982:11)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1696434674419%2Fbuild-a-nucleus%2Fbuild-a-nucleus_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26decayScreenProtons%3D58%26decayScreenNeutrons%3D92%26chartIntoScreenProtons%3D8%26chartIntoScreenNeutrons%3D12&testInfo=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1696434674419%22%2C%22timestamp%22%3A1696435257585%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1696434674419%2Fbuild-a-nucleus%2Fbuild-a-nucleus_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26decayScreenProtons%3D58%26decayScreenNeutrons%3D92%26chartIntoScreenProtons%3D8%26chartIntoScreenNeutrons%3D12&testInfo=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1696434674419%22%2C%22timestamp%22%3A1696435257585%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1696434674419%22%2C%22timestamp%22%3A1696435257585%7D&brand=phet&ea&fuzz&decayScreenProtons=58&decayScreenNeutrons=92&chartIntoScreenProtons=8&chartIntoScreenNeutrons=12
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: cannot step a particle that has already been disposed
[PAGE ERROR] Error: Error: Assertion failed: cannot step a particle that has already been disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/assert/js/assert.js:28:13)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:162:17
at Proxy.forEach (<anonymous>)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:161:20)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/decay/model/DecayModel.js:75:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:339:22
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
at Sim.stepSimulation (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:856:31)
at Sim.stepOneFrame (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:846:12)
at Sim.runAnimationLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:824:12)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: cannot step a particle that has already been disposed
[PAGE ERROR] Error: Error: Assertion failed: cannot step a particle that has already been disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/assert/js/assert.js:28:13)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:162:17
at Proxy.forEach (<anonymous>)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:161:20)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/decay/model/DecayModel.js:75:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:339:22
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
at Sim.stepSimulation (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:856:31)
at Sim.stepOneFrame (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:846:12)
at Sim.runAnimationLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:824:12)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: cannot step a particle that has already been disposed
[PAGE ERROR] Error: Error: Assertion failed: cannot step a particle that has already been disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/assert/js/assert.js:28:13)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:162:17
at Proxy.forEach (<anonymous>)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:161:20)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/decay/model/DecayModel.js:75:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:339:22
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
at Sim.stepSimulation (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:856:31)
at Sim.stepOneFrame (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:846:12)
at Sim.runAnimationLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:824:12)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: cannot step a particle that has already been disposed
[PAGE ERROR] Error: Error: Assertion failed: cannot step a particle that has already been disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/assert/js/assert.js:28:13)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:162:17
at Proxy.forEach (<anonymous>)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:161:20)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/decay/model/DecayModel.js:75:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:339:22
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
at Sim.stepSimulation (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:856:31)
at Sim.stepOneFrame (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:846:12)
at Sim.runAnimationLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:824:12)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: cannot step a particle that has already been disposed
[PAGE ERROR] Error: Error: Assertion failed: cannot step a particle that has already been disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/assert/js/assert.js:28:13)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:162:17
at Proxy.forEach (<anonymous>)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:161:20)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/decay/model/DecayModel.js:75:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:339:22
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
at Sim.stepSimulation (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:856:31)
at Sim.stepOneFrame (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:846:12)
at Sim.runAnimationLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:824:12)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: cannot step a particle that has already been disposed
[PAGE ERROR] Error: Error: Assertion failed: cannot step a particle that has already been disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/assert/js/assert.js:28:13)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:162:17
at Proxy.forEach (<anonymous>)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:161:20)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/decay/model/DecayModel.js:75:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:339:22
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
at Sim.stepSimulation (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:856:31)
at Sim.stepOneFrame (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:846:12)
at Sim.runAnimationLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:824:12)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: cannot step a particle that has already been disposed
[PAGE ERROR] Error: Error: Assertion failed: cannot step a particle that has already been disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/assert/js/assert.js:28:13)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:162:17
at Proxy.forEach (<anonymous>)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:161:20)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/decay/model/DecayModel.js:75:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:339:22
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
at Sim.stepSimulation (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:856:31)
at Sim.stepOneFrame (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:846:12)
at Sim.runAnimationLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:824:12)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: cannot step a particle that has already been disposed
[PAGE ERROR] Error: Error: Assertion failed: cannot step a particle that has already been disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/assert/js/assert.js:28:13)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:162:17
at Proxy.forEach (<anonymous>)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:161:20)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/decay/model/DecayModel.js:75:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:339:22
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
at Sim.stepSimulation (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:856:31)
at Sim.stepOneFrame (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:846:12)
at Sim.runAnimationLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:824:12)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: cannot step a particle that has already been disposed
[PAGE ERROR] Error: Error: Assertion failed: cannot step a particle that has already been disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/assert/js/assert.js:28:13)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:162:17
at Proxy.forEach (<anonymous>)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:161:20)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/decay/model/DecayModel.js:75:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:339:22
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
at Sim.stepSimulation (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:856:31)
at Sim.stepOneFrame (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:846:12)
at Sim.runAnimationLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:824:12)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: cannot step a particle that has already been disposed
[PAGE ERROR] Error: Error: Assertion failed: cannot step a particle that has already been disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/assert/js/assert.js:28:13)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:162:17
at Proxy.forEach (<anonymous>)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:161:20)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/decay/model/DecayModel.js:75:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:339:22
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
at Sim.stepSimulation (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:856:31)
at Sim.stepOneFrame (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:846:12)
at Sim.runAnimationLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:824:12)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: cannot step a particle that has already been disposed
[PAGE ERROR] Error: Error: Assertion failed: cannot step a particle that has already been disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/assert/js/assert.js:28:13)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:162:17
at Proxy.forEach (<anonymous>)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:161:20)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/decay/model/DecayModel.js:75:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:339:22
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
at Sim.stepSimulation (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:856:31)
at Sim.stepOneFrame (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:846:12)
at Sim.runAnimationLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:824:12)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: cannot step a particle that has already been disposed
[PAGE ERROR] Error: Error: Assertion failed: cannot step a particle that has already been disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/assert/js/assert.js:28:13)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:162:17
at Proxy.forEach (<anonymous>)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/common/model/BANModel.js:161:20)
at DecayModel.step (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/build-a-nucleus/js/decay/model/DecayModel.js:75:11)
at http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:339:22
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/tandem/js/PhetioAction.js:132:17)
at Sim.stepSimulation (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:856:31)
at Sim.stepOneFrame (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:846:12)
at Sim.runAnimationLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1696434674419/chipper/dist/js/joist/js/Sim.js:824:12)

id: "Sparky Node Puppeteer"
Snapshot from 10/4/2023, 11:51:14 AM
```

**Comment by Luisav1** [comment]
So far couldn't reproduce with fuzzing but I know:
- only happens on the decay screen
- the problematic particle is always a neutron
- the neutron particle only remains in `this.particles` when it shouldn't, all other arrays (`userControlledNeutrons`, `incomingNeutrons`, `outgoingParticles`) are clear of this particle

**Comment by zepumph** [comment]
I wonder if this is happening downstream of what we tried to fix with https://github.com/phetsims/build-a-nucleus/blob/e15b04d26ef16b510eb94f44300d5a33c86f963e/js/common/view/BANScreenView.ts#L126 over in https://github.com/phetsims/build-a-nucleus/issues/115.

Maybe that's a red herring, sorry if it is! But we could assert to see if there are any animations hanging around after reset for this disposed entity. Or perhaps the bug that is causing this particle to not be in any list is also causing its animations to not be in any list, so the Animation can't be stopped (and thus runs things on a disposed particle).

**Comment by Luisav1** [comment]
Added id log after rest to particles that couldn't be cleared and had to manually be cleared above. Also added id log to the CT assertion. Will see if they're the same particle.

**Comment by Luisav1** [comment]
Turns out they are the same particle from this CT snippet:
```js
Query: brand=phet&ea&fuzz&decayScreenProtons=46&decayScreenNeutrons=58&chartIntoScreenProtons=2&chartIntoScreenNeutrons=3
Uncaught Error: Assertion failed: Cannot step a particle that has already been disposed: neutron false id 105
Error: Assertion failed: Cannot step a particle that has already been disposed: neutron false id 105
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1696958932259/assert/js/assert.js:28:13)
at assert (BANModel.ts:215:16)
at Proxy.forEach
at forEach (BANModel.ts:214:19)
at step (DecayModel.ts:121:10)
at step (Sim.ts:417:21)
at apply (PhetioAction.ts:161:16)
at execute (Sim.ts:1017:30)
at stepSimulation (Sim.ts:1007:11)
at stepOneFrame (Sim.ts:982:11)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1696958932259%2Fbuild-a-nucleus%2Fbuild-a-nucleus_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26decayScreenProtons%3D46%26decayScreenNeutrons%3D58%26chartIntoScreenProtons%3D2%26chartIntoScreenNeutrons%3D3&testInfo=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1696958932259%22%2C%22timestamp%22%3A1696959861137%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1696958932259%2Fbuild-a-nucleus%2Fbuild-a-nucleus_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26decayScreenProtons%3D46%26decayScreenNeutrons%3D58%26chartIntoScreenProtons%3D2%26chartIntoScreenNeutrons%3D3&testInfo=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1696958932259%22%2C%22timestamp%22%3A1696959861137%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1696958932259/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1696958932259%22%2C%22timestamp%22%3A1696959861137%7D&brand=phet&ea&fuzz&decayScreenProtons=46&decayScreenNeutrons=58&chartIntoScreenProtons=2&chartIntoScreenNeutrons=3
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[CONSOLE] Disposing particle with id 105
```

Turns out the bandaid fix we added above about clearing all particles that weren't attached to anything and left over after a reset, is also in turn removing a particle that is in the middle of animating such that when we step it we get the error that it's already been disposed.

**Comment by Luisav1** [comment]
In working on #210 with @zepumph we found that this issue is caused by resetting while decaying when you have any query parameters. So this blocks sim publication because there is an issue with the query parameters.

**Comment by zepumph** [comment]
This totally makes sense. We are disposing the new particles we just reset to! We can feel confident that anything in this.particles is from the query parameters, and call it good. We will also want to remove the assertion we added, since reset will actually create particles in that case.

**Comment by zepumph** [comment]
Working on this now.

**Comment by zepumph** [comment]
Ok. The fix was working when resetting with the query parameters now. I pushed it to the branch and we are ready to verify for QA next RC spot check.

For QA:
Please test a fair amount with the following query parameters to make sure they are behaving correctly. These are public parameters and we should have asked for testing in the original RC. Their max allowed values are the max that you can get to within the arrow buttons in the sim, but should gracefully support incorrect numbers too. Feel free to close.

```
decayScreenNeutrons
decayScreenProtons
chartIntroScreenNeutrons
chartIntroScreenProtons
```

**Comment by KatieWoe** [comment]
I ran a fuzz test on the debug version with chartIntroScreenNeutrons and chartIntroScreenProtons and got these errors, though it didn't freeze the sim.
![fuzzerror](https://github.com/phetsims/build-a-nucleus/assets/41024075/a0c40e17-fc3d-4bbd-a673-1cf76567a353)

**Comment by zepumph** [comment]
Easily reproduced with http://localhost:8080/build-a-nucleus/build-a-nucleus_en.html?brand=phet&ea&debugger&locales=*&keyboardLocaleSwitcher&stringTest=dynamic&chartIntroScreenNeutrons=5&chartIntroScreenProtons=6&fuzz

Also can reproduce with http://localhost:8080/build-a-nucleus/build-a-nucleus_en.html?brand=phet&ea&debugger&chartIntroScreenNeutrons=5&chartIntroScreenProtons=6&fuzz

Also, for unbuilt mode we needed https://github.com/phetsims/shred/commit/5dd7b6c1c6d13d988e0b9be5295a8c177a0a5d3d because we were hitting an assertion that didn't matter or effect our case. No need to cherry pick that because it is rare and the assertion won't trigger in built mode.

**Comment by zepumph** [comment]
Shoot! @Luisav1, we were checking on `this.particles`, but the mini atom particles aren't part of that. Frustrating! Let's see if CT is clean tomorrow morning.

**Comment by zepumph** [comment]
CT is clear, and I'm going to cherry pick 3d4c77b658824c690304750e4d47393326110b53 to the branch now. The query parameters are working well on my side with local testing. I think we are ready to publish.

**Comment by zepumph** [comment]
Ready to close @Luisav1?

**Comment by zepumph** [comment]
We discussed and are ready.
