### ISSUE TITLE
CT reentry detected

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#36]
```
build-a-nucleus : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1656852792001/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1656852792001%22%2C%22timestamp%22%3A1656863235695%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=Vector2(-222.9626132852826, 239.200069140871), oldValue=Vector2(-221.93984900415748, 238.10282111728904)
Error: Assertion failed: reentry detected, value=Vector2(-222.9626132852826, 239.200069140871), oldValue=Vector2(-221.93984900415748, 238.10282111728904)
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1656852792001/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:256:14)
at _notifyListeners (ReadOnlyProperty.ts:210:13)
at set (Property.ts:67:10)
at set (Property.ts:53:9)
at (AnimationTarget.js:296:6)
at setValue (AnimationTarget.js:331:9)
at update (Animation.js:308:24)
at listener (TinyEmitter.ts:92:8)
at emit (Sim.ts:443:16)
id: Bayes Puppeteer
Snapshot from 7/3/2022, 6:53:12 AM

----------------------------------

build-a-nucleus : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1656852792001/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1656852792001%22%2C%22timestamp%22%3A1657024393602%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: reentry detected, value=Vector2(39.25126229475022, -311.94021608037104), oldValue=Vector2(37.67821552339572, -299.438795206921)
Error: Assertion failed: reentry detected, value=Vector2(39.25126229475022, -311.94021608037104), oldValue=Vector2(37.67821552339572, -299.438795206921)
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1656852792001/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:256:14)
at _notifyListeners (ReadOnlyProperty.ts:210:13)
at set (Property.ts:67:10)
at set (Property.ts:53:9)
at (AnimationTarget.js:296:6)
at setValue (AnimationTarget.js:331:9)
at update (Animation.js:308:24)
at listener (TinyEmitter.ts:92:8)
at emit (Sim.ts:443:16)
id: Bayes Puppeteer
Snapshot from 7/3/2022, 6:53:12 AM

----------------------------------

build-a-nucleus : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1656852792001/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1656852792001%22%2C%22timestamp%22%3A1656891368548%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: The particleAtom needs a PROTON to emit it. The decay: alpha decay cannot occur.
Error: Assertion failed: The particleAtom needs a PROTON to emit it. The decay: alpha decay cannot occur.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1656852792001/assert/js/assert.js:28:13)
at assert (DecayScreenView.ts:383:14)
at emitNucleon (DecayScreenView.ts:474:35)
at baseTimes (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1656852792001/sherpa/lib/lodash-4.17.4.js:997:23)
at Function.times (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1656852792001/sherpa/lib/lodash-4.17.4.js:16095:20)
at times (DecayScreenView.ts:474:12)
at listener (TinyEmitter.ts:92:8)
at emit (ReadOnlyProperty.ts:259:22)
at _notifyListeners (ReadOnlyProperty.ts:210:13)
at set (Property.ts:67:10)
id: Bayes Puppeteer
Snapshot from 7/3/2022, 6:53:12 AM

----------------------------------

build-a-nucleus : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1656852792001/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1656852792001%22%2C%22timestamp%22%3A1657030545396%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: The particleAtom needs a PROTON to emit it. The decay: alpha decay cannot occur.
Error: Assertion failed: The particleAtom needs a PROTON to emit it. The decay: alpha decay cannot occur.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1656852792001/assert/js/assert.js:28:13)
at assert (DecayScreenView.ts:383:14)
at emitNucleon (DecayScreenView.ts:474:35)
at baseTimes (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1656852792001/sherpa/lib/lodash-4.17.4.js:997:23)
at Function.times (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1656852792001/sherpa/lib/lodash-4.17.4.js:16095:20)
at times (DecayScreenView.ts:474:12)
at listener (TinyEmitter.ts:92:8)
at emit (ReadOnlyProperty.ts:259:22)
at _notifyListeners (ReadOnlyProperty.ts:210:13)
at set (Property.ts:67:10)
id: Bayes Puppeteer
Snapshot from 7/3/2022, 6:53:12 AM
```

**Comment by Luisav1** [comment]
We've looked at this quite a bit, it's pretty hard reproduce. So it's not an issue for the prototype.

**Comment by KatieWoe** [comment]
Running the debug version of rc.8 with a fuzz test didn't seem to replicate this.

**Comment by zepumph** [comment]
CT has been clear for the last 12 hours. Closing
