### ISSUE TITLE
CT Color stops not specified in the order of increasing ratios

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#49]
```
build-a-nucleus : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661514776765%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught Error: Color stops not specified in the order of increasing ratios
Error: Color stops not specified in the order of increasing ratios
at jn.addColorStop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661514776765%7D&fuzz&memoryLimit=1000:894:388151)
at f (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661514776765%7D&fuzz&memoryLimit=1000:894:1140342)
at Ls.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661514776765%7D&fuzz&memoryLimit=1000:894:14448)
at Ls.notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661514776765%7D&fuzz&memoryLimit=1000:894:427020)
at Fa.validateSelfBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661514776765%7D&fuzz&memoryLimit=1000:894:435372)
at Fa.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661514776765%7D&fuzz&memoryLimit=1000:894:435433)
at Ls.get (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661514776765%7D&fuzz&memoryLimit=1000:894:426880)
at Ls.get value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661514776765%7D&fuzz&memoryLimit=1000:894:15487)
at Fa.getLocalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661514776765%7D&fuzz&memoryLimit=1000:894:438701)
at Fa.get localBounds [as localBounds] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661514776765%7D&fuzz&memoryLimit=1000:894:438737)
id: Bayes Puppeteer
Snapshot from 8/26/2022, 3:59:33 AM

----------------------------------

build-a-nucleus : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661518760676%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught Error: Color stops not specified in the order of increasing ratios
Error: Color stops not specified in the order of increasing ratios
at jn.addColorStop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661518760676%7D&fuzz&memoryLimit=1000:894:388151)
at f (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661518760676%7D&fuzz&memoryLimit=1000:894:1140342)
at Ls.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661518760676%7D&fuzz&memoryLimit=1000:894:14448)
at Ls.notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661518760676%7D&fuzz&memoryLimit=1000:894:427020)
at Fa.validateSelfBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661518760676%7D&fuzz&memoryLimit=1000:894:435372)
at Fa.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661518760676%7D&fuzz&memoryLimit=1000:894:435433)
at Ls.get (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661518760676%7D&fuzz&memoryLimit=1000:894:426880)
at Ls.get value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661518760676%7D&fuzz&memoryLimit=1000:894:15487)
at Fa.getLocalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661518760676%7D&fuzz&memoryLimit=1000:894:438701)
at Fa.get localBounds [as localBounds] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661518760676%7D&fuzz&memoryLimit=1000:894:438737)
id: Bayes Puppeteer
Snapshot from 8/26/2022, 3:59:33 AM

----------------------------------

build-a-nucleus : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661512578709%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/assert/js/assert.js:28:13)
at assert (RectangularButton.ts:291:16)
at listener (TinyEmitter.ts:95:8)
at emit (TinyStaticProperty.ts:56:9)
at notifyListeners (Node.ts:1347:32)
at validateSelfBounds (Node.ts:1370:30)
at onAccessAttempt (TinyStaticProperty.ts:31:9)
at get (TinyProperty.ts:56:16)
at value (Node.ts:1804:36)
at getLocalBounds (Node.ts:1811:16)
id: Bayes Puppeteer
Snapshot from 8/26/2022, 3:59:33 AM

----------------------------------

build-a-nucleus : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661518362444%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/assert/js/assert.js:28:13)
at assert (RectangularButton.ts:291:16)
at listener (TinyEmitter.ts:95:8)
at emit (TinyStaticProperty.ts:56:9)
at notifyListeners (Node.ts:1347:32)
at validateSelfBounds (Node.ts:1370:30)
at onAccessAttempt (TinyStaticProperty.ts:31:9)
at get (TinyProperty.ts:56:16)
at value (Node.ts:1804:36)
at getLocalBounds (Node.ts:1811:16)
id: Bayes Puppeteer
Snapshot from 8/26/2022, 3:59:33 AM

----------------------------------

build-a-nucleus : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661512829521%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/assert/js/assert.js:28:13)
at assert (RectangularButton.ts:291:16)
at listener (TinyEmitter.ts:95:8)
at emit (TinyStaticProperty.ts:56:9)
at notifyListeners (Node.ts:1347:32)
at validateSelfBounds (Node.ts:1370:30)
at onAccessAttempt (TinyStaticProperty.ts:31:9)
at get (TinyProperty.ts:56:16)
at value (Node.ts:1804:36)
at getLocalBounds (Node.ts:1811:16)
id: Bayes Puppeteer
Snapshot from 8/26/2022, 3:59:33 AM

----------------------------------

build-a-nucleus : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661525626142%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/assert/js/assert.js:28:13)
at assert (RectangularButton.ts:291:16)
at listener (TinyEmitter.ts:95:8)
at emit (TinyStaticProperty.ts:56:9)
at notifyListeners (Node.ts:1347:32)
at validateSelfBounds (Node.ts:1370:30)
at onAccessAttempt (TinyStaticProperty.ts:31:9)
at get (TinyProperty.ts:56:16)
at value (Node.ts:1804:36)
at getLocalBounds (Node.ts:1811:16)
id: Bayes Puppeteer
Snapshot from 8/26/2022, 3:59:33 AM

----------------------------------

build-a-nucleus : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661512831963%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/assert/js/assert.js:28:13)
at assert (RectangularButton.ts:291:16)
at listener (TinyEmitter.ts:95:8)
at emit (TinyStaticProperty.ts:56:9)
at notifyListeners (Node.ts:1347:32)
at validateSelfBounds (Node.ts:1370:30)
at onAccessAttempt (TinyStaticProperty.ts:31:9)
at get (TinyProperty.ts:56:16)
at value (Node.ts:1804:36)
at getLocalBounds (Node.ts:1811:16)
id: Bayes Puppeteer
Snapshot from 8/26/2022, 3:59:33 AM

----------------------------------

build-a-nucleus : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1661507973361%22%2C%22timestamp%22%3A1661512494712%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661507973361/assert/js/assert.js:28:13)
at assert (RectangularButton.ts:291:16)
at listener (TinyEmitter.ts:95:8)
at emit (TinyStaticProperty.ts:56:9)
at notifyListeners (Node.ts:1347:32)
at validateSelfBounds (Node.ts:1370:30)
at onAccessAttempt (TinyStaticProperty.ts:31:9)
at get (TinyProperty.ts:56:16)
at value (Node.ts:1804:36)
at getLocalBounds (Node.ts:1811:16)
id: Bayes Puppeteer
Snapshot from 8/26/2022, 3:59:33 AM
```

**Comment by chrisklus** [comment]
Thanks @KatieWoe! @Luisav1 and I have been looking into this - right now when the sim starts up, there is an assertion firing in RectangularButton that the height does not meet minimum requirements (`assert && assert( buttonHeight >= VERTICAL_HIGHLIGHT_GRADIENT_LENGTH + SHADE_GRADIENT_LENGTH );`). 

We've traced it to the "down" set of arrows created in DoubleArrowButton:

```js
      if ( direction === 'down' ) {
        doubleArrow.setRotation( Math.PI );

        // switch the colors since the arrow was rotated 180 degrees
        leftArrowPath.fill = rightArrowFill;
        rightArrowPath.fill = leftArrowFill;
      }
```

If we comment out `doubleArrow.setRotation( Math.PI );`, the problem does not occur. So we think something about that rotation is causing weird bounds. Weirdly, adding `widthSizable: false` to DoubleArrowButton does not seem to help the problem.

Any ideas @jonathanolson?

**Comment by Luisav1** [comment]
Adding `heightSizable: false` to the DoubleArrowButton fixes the problem but it causes the 'down' DoubleArrowButton to look like this.
![image](https://user-images.githubusercontent.com/52978048/186981974-57d7d69d-7607-4bbc-addd-26ccb9c9395a.png)

**Comment by zepumph** [comment]
We don't see this on CT right now, but it may be just hidden by other errors. Marking on hold and removing assignment.

**Comment by zepumph** [comment]
CT has been clear for the last 12 hours. Closing
