### ISSUE TITLE
CT class constructor LinearFunction cannot be invoked without new

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#5]
```
build-a-nucleus : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1637662989114%22%2C%22timestamp%22%3A1637664860149%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: Class constructor LinearFunction cannot be invoked without 'new'
TypeError: Class constructor LinearFunction cannot be invoked without 'new'
at ParticleAtom.reconfigureNucleus (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/shred/js/model/ParticleAtom.js:469:35)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/shred/js/view/ElectronShellView.js:131:18
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/axon/js/Multilink.js:37:21)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/axon/js/TinyEmitter.js:65:17)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/axon/js/Property.js:193:27)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/axon/js/Property.js:137:22)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/axon/js/DerivedProperty.js:83:19)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/axon/js/TinyEmitter.js:65:17)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/axon/js/Property.js:193:27)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/axon/js/Property.js:137:22)
id: Bayes Chrome
Snapshot from 11/23/2021, 3:23:09 AM
```

**Comment by Luisav1** [comment]
The LinearFunction issue does not sow up anymore on CT. Closing.
