### ISSUE TITLE
CT item not found in Array

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#62]
```
build-a-nucleus : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667836380449%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/assert/js/assert.js:28:13)
at assert (arrayRemove.js:19:12)
at arrayRemove (createObservableArray.ts:393:37)
at remove (BANModel.ts:128:19)
at removeParticle (DecayScreenView.ts:122:19)
at Proxy.forEach
at forEach (DecayScreenView.ts:121:35)
at listener (TinyEmitter.ts:95:8)
at emit (Emitter.ts:60:21)
at emit (PushButtonModel.ts:179:22)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 6:25:56 AM

----------------------------------

build-a-nucleus : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1667827556469%22%2C%22timestamp%22%3A1667836462233%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667827556469/assert/js/assert.js:28:13)
at assert (arrayRemove.js:19:12)
at arrayRemove (createObservableArray.ts:393:37)
at remove (BANModel.ts:128:19)
at removeParticle (DecayScreenView.ts:122:19)
at Proxy.forEach
at forEach (DecayScreenView.ts:121:35)
at listener (TinyEmitter.ts:95:8)
at emit (Emitter.ts:60:21)
at emit (PushButtonModel.ts:179:22)
id: Bayes Puppeteer
Snapshot from 11/7/2022, 6:25:56 AM
```

**Comment by Luisav1** [comment]
Thanks @KatieWoe! @chrisklus, @marlitas, and I fixed this in the commit above. We didn't see it come up again after several rounds of CT. Closing.
