### ISSUE TITLE
CT Cannot read properties of undefined (reading 'createTandem')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#67]
```
build-a-nucleus : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1673343886958/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1673343886958%22%2C%22timestamp%22%3A1673347098738%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'createTandem')
TypeError: Cannot read properties of undefined (reading 'createTandem')
at jg.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1673343886958/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1673343886958%22%2C%22timestamp%22%3A1673347098738%7D&fuzz&memoryLimit=1000:975:1711042)
at jg.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1673343886958/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1673343886958%22%2C%22timestamp%22%3A1673347098738%7D&fuzz&memoryLimit=1000:975:1230503)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1673343886958/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1673343886958%22%2C%22timestamp%22%3A1673347098738%7D&fuzz&memoryLimit=1000:975:1506075)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1673343886958/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1673343886958%22%2C%22timestamp%22%3A1673347098738%7D&fuzz&memoryLimit=1000:975:1506252)
id: Bayes Puppeteer
Snapshot from 1/10/2023, 2:44:46 AM

----------------------------------

build-a-nucleus : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1673343886958/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1673343886958%22%2C%22timestamp%22%3A1673353040517%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'createTandem')
TypeError: Cannot read properties of undefined (reading 'createTandem')
at jg.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1673343886958/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1673343886958%22%2C%22timestamp%22%3A1673353040517%7D&fuzz&memoryLimit=1000:975:1711042)
at jg.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1673343886958/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1673343886958%22%2C%22timestamp%22%3A1673353040517%7D&fuzz&memoryLimit=1000:975:1230503)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1673343886958/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1673343886958%22%2C%22timestamp%22%3A1673353040517%7D&fuzz&memoryLimit=1000:975:1506075)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1673343886958/build-a-nucleus/build/phet/build-a-nucleus_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1673343886958%22%2C%22timestamp%22%3A1673353040517%7D&fuzz&memoryLimit=1000:975:1506252)
id: Bayes Puppeteer
Snapshot from 1/10/2023, 2:44:46 AM

----------------------------------

build-a-nucleus : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1673343886958/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1673343886958%22%2C%22timestamp%22%3A1673346996458%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'createTandem')
TypeError: Cannot read properties of undefined (reading 'createTandem')
at createTandem (DecayScreen.ts:33:53)
at createModel (Screen.ts:291:23)
at initializeModel (Sim.ts:878:15)
at (Sim.ts:889:10)
id: Bayes Puppeteer
Snapshot from 1/10/2023, 2:44:46 AM

----------------------------------

build-a-nucleus : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1673343886958/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1673343886958%22%2C%22timestamp%22%3A1673353477033%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'createTandem')
TypeError: Cannot read properties of undefined (reading 'createTandem')
at createTandem (DecayScreen.ts:33:53)
at createModel (Screen.ts:291:23)
at initializeModel (Sim.ts:878:15)
at (Sim.ts:889:10)
id: Bayes Puppeteer
Snapshot from 1/10/2023, 2:44:46 AM

----------------------------------

build-a-nucleus : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1673343886958/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1673343886958%22%2C%22timestamp%22%3A1673351473679%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'createTandem')
TypeError: Cannot read properties of undefined (reading 'createTandem')
at createTandem (DecayScreen.ts:33:53)
at createModel (Screen.ts:291:23)
at initializeModel (Sim.ts:878:15)
at (Sim.ts:889:10)
id: Bayes Puppeteer
Snapshot from 1/10/2023, 2:44:46 AM

----------------------------------

build-a-nucleus : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1673343886958/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1673343886958%22%2C%22timestamp%22%3A1673353549199%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: Cannot read properties of undefined (reading 'createTandem')
TypeError: Cannot read properties of undefined (reading 'createTandem')
at createTandem (DecayScreen.ts:33:53)
at createModel (Screen.ts:291:23)
at initializeModel (Sim.ts:878:15)
at (Sim.ts:889:10)
id: Bayes Puppeteer
Snapshot from 1/10/2023, 2:44:46 AM

----------------------------------

build-a-nucleus : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1673343886958/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1673343886958%22%2C%22timestamp%22%3A1673347336654%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot read properties of undefined (reading 'createTandem')
TypeError: Cannot read properties of undefined (reading 'createTandem')
at createTandem (DecayScreen.ts:33:53)
at createModel (Screen.ts:291:23)
at initializeModel (Sim.ts:878:15)
at (Sim.ts:889:10)
id: Bayes Puppeteer
Snapshot from 1/10/2023, 2:44:46 AM

----------------------------------

build-a-nucleus : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1673343886958/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1673343886958%22%2C%22timestamp%22%3A1673352988377%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot read properties of undefined (reading 'createTandem')
TypeError: Cannot read properties of undefined (reading 'createTandem')
at createTandem (DecayScreen.ts:33:53)
at createModel (Screen.ts:291:23)
at initializeModel (Sim.ts:878:15)
at (Sim.ts:889:10)
id: Bayes Puppeteer
Snapshot from 1/10/2023, 2:44:46 AM

----------------------------------

build-a-nucleus : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1673343886958/build-a-nucleus/build-a-nucleus_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-nucleus%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1673343886958%22%2C%22timestamp%22%3A1673346644799%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'createTandem')
TypeError: Cannot read properties of undefined (reading 'createTandem')
at createTandem (DecayScreen.ts:33:53)
at createModel (Screen.ts:291:23)
at initializeModel (Sim.ts:878:15)
at (Sim.ts:889:10)
id: Bayes Puppeteer
Snapshot from 1/10/2023, 2:44:46 AM
```

**Comment by Luisav1** [comment]
Thanks Katie! @marlitas and I removed all cases where tandem was created in https://github.com/phetsims/build-a-nucleus/commit/b31a8d95663b22881d7e52366d70de6356d4e0ea since BaN isn't phet-io instrumented.

**Comment by marlitas** [comment]
With those commits I believe this issue can be closed. Thanks!
